module fr.rhumun.game.worldcraftopengl {
    requires javafx.controls;
    requires javafx.fxml;
    requires org.lwjgl.glfw;
    requires org.lwjgl.opengl;
    requires static lombok;
    requires org.lwjgl.stb;
    requires org.joml;
    requires org.lwjgl.openal;
    requires org.lwjgl.nuklear;
    requires java.datatransfer;
    requires java.desktop;
    requires org.lwjgl.bgfx;
    requires org.lwjgl.opengles;
    requires JNOISE;
    requires core;
    requires generators;
    requires modules;
    requires obj;
    requires org.lwjgl.freetype;

    opens fr.rhumun.game.worldcraftopengl to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl;
    exports fr.rhumun.game.worldcraftopengl.outputs.graphic;
    opens fr.rhumun.game.worldcraftopengl.outputs.graphic to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl.content;
    opens fr.rhumun.game.worldcraftopengl.content to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl.worlds;
    opens fr.rhumun.game.worldcraftopengl.worlds to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl.outputs.graphic.utils;
    opens fr.rhumun.game.worldcraftopengl.outputs.graphic.utils to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl.worlds.generators;
    opens fr.rhumun.game.worldcraftopengl.worlds.generators to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl.content.materials;
    opens fr.rhumun.game.worldcraftopengl.content.materials to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl.outputs.graphic.renderers;
    opens fr.rhumun.game.worldcraftopengl.outputs.graphic.renderers to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl.outputs.graphic.shaders;
    opens fr.rhumun.game.worldcraftopengl.outputs.graphic.shaders to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl.content.materials.types;
    opens fr.rhumun.game.worldcraftopengl.content.materials.types to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl.content.textures;
    opens fr.rhumun.game.worldcraftopengl.content.textures to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl.content.materials.opacity;
    opens fr.rhumun.game.worldcraftopengl.content.materials.opacity to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl.outputs.graphic.utils.models;
    opens fr.rhumun.game.worldcraftopengl.outputs.graphic.utils.models to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl.entities;
    opens fr.rhumun.game.worldcraftopengl.entities to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl.content.items;
    opens fr.rhumun.game.worldcraftopengl.content.items to javafx.fxml;
    exports fr.rhumun.game.worldcraftopengl.entities.physics;
    opens fr.rhumun.game.worldcraftopengl.entities.physics to javafx.fxml;
}